In [1]:
import numpy as np

In [2]:
sizes = [3, 5, 2]

In [3]:
biases = [np.random.randn(y, 1) for y in sizes[1:]]

In [5]:
weight = [np.random.randn(y, x) for x,y in zip(sizes[:-1], sizes[1:])]

In [11]:
training = [(np.array([[ 0.2        ],
                       [ 0.5        ],
                       [ 0.1        ],
            ]), np.array([[ 1.],
                          [ 0.]])), 
            (np.array([[ 0.7        ],
                       [ 0       ],
                       [ 1        ],
            ]), np.array([[ 1.],
                          [ 0.]]))       ]

In [130]:
x_train = np.concatenate([tr[0] for tr in training], axis = 1)
y_train = np.concatenate([tr[1] for tr in training], axis = 1)
x_train

array([[ 0.2,  0.7],
       [ 0.5,  0. ],
       [ 0.1,  1. ]])

In [129]:
np.concatenate(np.array(training)[:,0], axis = 1)

array([[ 0.2,  0.7],
       [ 0.5,  0. ],
       [ 0.1,  1. ]])

In [19]:
weight[0].dot(x_train)

array([[-0.24202113,  1.12906856],
       [-0.24724052,  0.34361366],
       [ 0.88505188,  1.54315972],
       [ 0.03003055,  0.73898645],
       [ 0.32560379, -0.63760532]])

In [21]:
weight[0].dot(x_train) + biases[0]

array([[-1.4963162 , -0.1252265 ],
       [-1.07302857, -0.48217439],
       [-1.23079902, -0.57269118],
       [ 1.24742517,  1.95638106],
       [ 2.19319816,  1.22998904]])

In [34]:
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

In [32]:
activation = x_train
activations = [x_train]
zs = []

In [35]:
for w, b in zip(weight, biases):
    z = w.dot(activation) + b
    activation = sigmoid(z)
    activations.append(activation)
    zs.append(z)

In [54]:
delta = (activations[2] - y_train)*zs[1]

In [106]:
zs[1].sum(axis = 1).reshape((len(zs[1]),1))

array([[ 6.47605321],
       [-0.70503177]])

In [56]:
delta

array([[-0.14670667, -0.10078685],
       [-0.03785349, -0.21815526]])

In [53]:
activations[1]

array([[ 0.18297559,  0.46873422],
       [ 0.25482756,  0.38173881],
       [ 0.22604161,  0.36061608],
       [ 0.77685383,  0.87614077],
       [ 0.89963704,  0.77381666]])

In [84]:
del_test = np.reshape(delta[:,0],(2,1))
act_test = np.reshape(activations[1][:,0],(5,1))
np.dot(del_test, act_test.transpose())

array([[-0.02684374, -0.0373849 , -0.03316181, -0.11396964, -0.13198276],
       [-0.00692627, -0.00964611, -0.00855646, -0.02940663, -0.03405441]])

In [107]:
C = np.einsum('ik,jk->kji', activations[1], delta)
C

array([[[-0.02684374, -0.0373849 , -0.03316181, -0.11396964, -0.13198276],
        [-0.00692627, -0.00964611, -0.00855646, -0.02940663, -0.03405441]],

       [[-0.04724225, -0.03847425, -0.03634536, -0.08830347, -0.07799054],
        [-0.10225683, -0.08327833, -0.07867029, -0.19113471, -0.16881217]]])

In [114]:
np.einsum('kij -> ij', C)

array([[-0.07408599, -0.07585916, -0.06950717, -0.20227311, -0.2099733 ],
       [-0.1091831 , -0.09292444, -0.08722676, -0.22054135, -0.20286658]])

In [112]:
C1 = np.einsum('ik,jk->ji', activations[1], delta)
C1

array([[-0.07408599, -0.07585916, -0.06950717, -0.20227311, -0.2099733 ],
       [-0.1091831 , -0.09292444, -0.08722676, -0.22054135, -0.20286658]])

In [118]:
np.einsum('ij -> i1', test)

ValueError: invalid subscript '1' in einstein sum subscripts string, subscripts must be letters

In [115]:
test = np.dot(weight[1].transpose(), delta)

In [119]:
np.sum(test, axis = 1)[:,None]

array([[ 0.22146592],
       [-0.80858483],
       [-0.16074511],
       [-0.03217207],
       [-0.49133479]])

In [113]:
np.reshape(a, (3,1)) 

array([[1],
       [3],
       [4]])

In [133]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [134]:
sigmoid(0.9+0.6)

0.81757447619364365